name       : pinentry
version    : 1.0.0
release    : 4
source     :
    - ftp://ftp.gnupg.org/gcrypt/pinentry/pinentry-1.0.0.tar.bz2 : 1672c2edc1feb036075b187c0773787b2afd0544f55025c645a71b4c2f79275a
homepage   : http://www.gnupg.org/aegypten/
license    :
    - GPL-2.0
summary    : Pin or pass-phrase entry dialog
component  : security
builddeps  :
    - pkgconfig(libsecret-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gcr-base-3)
    - libassuan-devel
description: |
    Pin or pass-phrase entry dialog
setup      : |
    %configure --with-pinentry-gnome3
build      : |
    %make
install    : |
    %make_install
