name       : pinentry
version    : 1.1.1
release    : 7
source     :
    - https://gnupg.org/ftp/gcrypt/pinentry/pinentry-1.1.1.tar.bz2 : cd12a064013ed18e2ee8475e669b9f58db1b225a0144debdb85a68cecddba57f
homepage   : https://gnupg.org/related_software/pinentry/
license    : GPL-2.0-or-later
summary    : Pin or pass-phrase entry dialog
description: |
    Pinentry is a collection of simple PIN or passphrase entry dialogs which utilize the Assuan protocol.
component  : security
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libassuan)
    - pkgconfig(libsecret-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
