name       : pinentry
version    : 1.1.0
release    : 6
source     :
    - https://gnupg.org/ftp/gcrypt/pinentry/pinentry-1.1.0.tar.bz2 : 68076686fa724a290ea49cdf0d1c0c1500907d1b759a3bcbfbec0293e8f56570
homepage   : https://gnupg.org/related_software/pinentry/
license    : GPL-2.0-or-later
summary    : Pin or pass-phrase entry dialog
description: |
    Pinentry is a collection of simple PIN or passphrase entry dialogs which utilize the Assuan protocol.
component  : security
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libassuan)
    - pkgconfig(libsecret-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
